#!/bin/bash +x
if [ 0 -lt $(id |grep -o -P '^uid=\d+' |cut -f2 -d=) ]
then
    echo -e "\e[5;31;47mWHA???\e[1;35;47m: Please rerun with sudo or as root\e[0m"
    exit 4
fi

Trigger_file='/var/lib/oem-config/run'
Last_RC=0
ls -l $Trigger_file 2>/dev/null || Last_RC=$?
if [ $Last_RC -gt 0 ]
then
    echo -e "\e[5;31;47mWHA???\e[1;35;47m: can't find $Trigger_file\e[0m"
    exit 5
fi

Last_RC=0
rm -iv $Trigger_file || Last_RC=$?
if [ $Last_RC -gt 0 ]
then
    echo -e "\n\e[1;32;47mSuccess!\e[0m\n"
    echo -e "\e[1;34;47mPreparing to reboot...\e[0m\n"
    /sbin/shutdown -r now
else
    echo -e "\e[5;31;47mWHA???\e[1;35;47m:Something weird is going on. Contact Staff.\e[0m"
    exit 6
fi

