user_pref("browser.safebrowsing.enabled", true);
user_pref("browser.safebrowsing.malware.enabled", true);
user_pref("general.autoScroll", false);
user_pref("general.smoothScroll", false);
#ser_pref("browser.startup.homepage", "https://google.com");
user_pref("browser.search.defaultenginename", "Google);
#ser_pref("browser.search.defaultthis.engineName", "Google");
user_pref("browser.search.order.1", "Google");
#ser_pref("browser.search.defaulturl", "https://www.google.com/search?ie=UTF-8&oe=UTF-8&q=");
user_pref("browser.tabs.animate", false);
#ser_pref("ui.submenuDelay", "0");
user_pref("security.tls.version.min", "1");
user_pref("keyword.URL", "https://www.google.com.my/search?q=");
user_pref("browser.newtabpage.enhanced", true)
